=begin
#OpenAPI Template

#A template OpenAPI specification.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/api_model_base'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/error'
require 'openapi_client/models/item'
require 'openapi_client/models/item_input'
require 'openapi_client/models/item_list'

# APIs
require 'openapi_client/api/items_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
