=begin
#OpenAPI Template

#A template OpenAPI specification.

The version of the OpenAPI document: 1.0.0
Contact: support@example.com
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

module OpenapiClient
  VERSION = '1.0.0'
end
